name: Pytorch Commit CI Trigger

on:
  workflow_dispatch:

jobs:
  trigger_test:
    uses: ./.github/workflows/_torch-npu-upstream-test.yml
    with:
      distributed_shards: '5'
      regular_shards: '5'
      test_files: ''
